Update bin scripts
Volume and keymap scripts have been mostly rewritten. There is a new
script for generating notifications.

diff --git a/bin/keymap b/bin/keymap
--- a/bin/keymap
+++ b/bin/keymap
@@ -1,50 +1,27 @@
-#!/bin/bash
-#DEP setxkbmap tr cut
-#OPT dunst dunstify xmodmap
+#! /usr/bin/env sh
 
-# Retrieve the current keymap
+# Retrieve current keymap
 lang="$(setxkbmap -query | grep layout | tr -d ' ' | cut -f2 -d':')"
-icon="" # requires font-awesome
-id_file="/tmp/.dunst_lang.id" # used if dunstify is installed
 
-
-# Make sure $lang isn't empty
-if [[ -z $lang ]]; then
-	echo "Error parsing keymap"
-	exit 1
+if [ $? -ne 0 ]; then
+    echo "Error parsing keymap"
+    exit 1
 fi
 
-
 # Toggle through keymaps
-if   [[ $lang == us ]]; then lang="ca"; setxkbmap $lang
-elif [[ $lang == ca ]]; then lang="us"; setxkbmap $lang
-
-# Default language
+if   [ "$lang" = us ]; then lang="ca"; setxkbmap $lang
+elif [ "$lang" = ca ]; then lang="us"; setxkbmap $lang
 else setxkbmap us
 fi
 
+# Generate notification
+text="$(echo $lang | tr '[:lower:]' '[:upper:]')"
+notif                     \
+    -n 1000               \
+    -i "$(basename "$0")" \
+    " $text"
 
-# Notification; uses dunst and dunstify
-if [[ -e $(which dunstify) ]]; then
-
-	# ID for replacing notification
-	id="$(cat $id_file)"
-
-	# Notification text
-	out="$icon $lang"
-
-	# if ID is valid, it is replace with -r
-	# -p prints the ID
-	if [[ $id -gt 0 ]]; then
-		dunstify -pr $id "$out" > $id_file
-	else
-		dunstify -p "$out" > $id_file
-	fi
-
-fi
-
-
-# Changing keymaps breaks xmodmap settings
-if [[ -e "$(which xmodmap)" && -f ~/.Xmodmap ]]; then
-	xmodmap ~/.Xmodmap &> /dev/null
+# Reload xmodmap
+if command -v xmodmap > /dev/null && [ -f "$HOME/.Xmodmap" ]; then
+    xmodmap "$HOME/.Xmodmap" > /dev/null
 fi
